### ISSUE TITLE
Inicializar  la aplicación movil App

### ISSUE THREAD

**Issue by Luis-Caxi-Calani** [XNICAL/CcontaPub-App#2]
Inicializar el proyecto móvil utilizando el framework seleccionado (React Native, Flutter, etc.).
Configurar e instalar las dependencias iniciales necesarias para el desarrollo de la aplicación (navegación, manejo de estado, etc.).

Criterios de aceptación:
- El proyecto base está creado con la estructura de carpetas adecuada.
- Se configuran los archivos principales (index.js, App.js, etc. en React Native; main.dart en Flutter).
- El proyecto se ejecuta correctamente en un emulador o dispositivo físico.

**Comment by josue-vy** [comment]
en hardware se eligió el pixel 5 por su mayor compatibilidad con diferentes teléfonos y en API escogimos el 31(Android 12) ya que también es compatible con diferentes teléfonos.


![Image](https://github.com/user-attachments/assets/ead6d198-ca76-4505-9861-13d72ebacbb7)

aquí probamos de forma local con el emulador designado 


![Image](https://github.com/user-attachments/assets/a6715191-8b53-4029-bee5-347cd83893f6)
![Image](https://github.com/user-attachments/assets/2abffe66-87e2-4dab-bdb1-800815cece3c)
